module.exports = [
  {
    dispensary_id: 1,
    day_of_week: 0,
    open_time: "",
    close_time: "",
  },
  {
    dispensary_id: 1,
    day_of_week: 1,
    open_time: "09:00 AM",
    close_time: "08:00 PM",
  },
  {
    dispensary_id: 1,
    day_of_week: 2,
    open_time: "09:00 AM",
    close_time: "08:00 PM",
  },
  {
    dispensary_id: 1,
    day_of_week: 3,
    open_time: "09:00 AM",
    close_time: "08:00 PM",
  },
  {
    dispensary_id: 1,
    day_of_week: 4,
    open_time: "09:00 AM",
    close_time: "08:00 PM",
  },
  {
    dispensary_id: 1,
    day_of_week: 5,
    open_time: "09:00 AM",
    close_time: "08:00 PM",
  },
  {
    dispensary_id: 1,
    day_of_week: 6,
    open_time: "",
    close_time: "",
  },

  {
    dispensary_id: 2,
    day_of_week: 0,
    open_time: "08:30 AM",
    close_time: "7:45 PM",
  },
  {
    dispensary_id: 2,
    day_of_week: 1,
    open_time: "08:30 AM",
    close_time: "7:45 PM",
  },
  {
    dispensary_id: 2,
    day_of_week: 2,
    open_time: "08:30 AM",
    close_time: "7:45 PM",
  },
  {
    dispensary_id: 2,
    day_of_week: 3,
    open_time: "08:30 AM",
    close_time: "7:45 PM",
  },
  {
    dispensary_id: 2,
    day_of_week: 4,
    open_time: "08:30 AM",
    close_time: "7:45 PM",
  },
  {
    dispensary_id: 2,
    day_of_week: 5,
    open_time: "",
    close_time: "",
  },
  {
    dispensary_id: 2,
    day_of_week: 6,
    open_time: "",
    close_time: "",
  },

  {
    dispensary_id: 3,
    day_of_week: 0,
    open_time: "",
    close_time: "",
  },
  {
    dispensary_id: 3,
    day_of_week: 1,
    open_time: "",
    close_time: "",
  },
  {
    dispensary_id: 3,
    day_of_week: 2,
    open_time: "10:00 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 3,
    day_of_week: 3,
    open_time: "10:00 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 3,
    day_of_week: 4,
    open_time: "10:00 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 3,
    day_of_week: 5,
    open_time: "10:00 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 3,
    day_of_week: 6,
    open_time: "10:00 AM",
    close_time: "11:00 PM",
  },

  {
    dispensary_id: 4,
    day_of_week: 0,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 4,
    day_of_week: 1,
    open_time: "",
    close_time: "",
  },
  {
    dispensary_id: 4,
    day_of_week: 2,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 4,
    day_of_week: 3,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 4,
    day_of_week: 4,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 4,
    day_of_week: 5,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 4,
    day_of_week: 6,
    open_time: "11:00 AM",
    close_time: "12:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 0,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 1,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 2,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 3,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 4,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 5,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
  {
    dispensary_id: 5,
    day_of_week: 6,
    open_time: "10:30 AM",
    close_time: "11:00 PM",
  },
];
