module.exports = [
  { effect: "Relaxed", effect_type: "positive" },
  { effect: "Hungry", effect_type: "positive" },
  { effect: "Happy", effect_type: "positive" },
  { effect: "Sleepy", effect_type: "positive" },
  { effect: "Euphoric", effect_type: "positive" },
  { effect: "Creative", effect_type: "positive" },
  { effect: "Energetic", effect_type: "positive" },
  { effect: "Talkative", effect_type: "positive" },
  { effect: "Dizzy", effect_type: "negative" },
  { effect: "Dry Mouth", effect_type: "negative" },
  { effect: "Paranoid", effect_type: "negative" },
  { effect: "Dry Eyes", effect_type: "negative" },
  { effect: "Anxious", effect_type: "negative" },
  { effect: "Depression", effect_type: "medical" },
  { effect: "Insomnia", effect_type: "medical" },
  { effect: "Pain", effect_type: "medical" },
  { effect: "Stress", effect_type: "medical" },
  { effect: "Lack of Appetite", effect_type: "medical" },
  { effect: "Nausea", effect_type: "medical" },
  { effect: "Headache", effect_type: "medical" },
  { effect: "Cramps", effect_type: "medical" },
];
