const bcrypt = require("bcrypt");

module.exports = [
  {
    first_name: "Aguste",
    last_name: "Bumpass",
    email: "59abumpass0@businessinsider.com",
    username: "abumpass086",
    password: bcrypt.hashSync("hP9YOx", 8),
    created_at: "2019-11-04",
  },
  {
    first_name: "Ely",
    last_name: "Bullerwell",
    email: "52ebullerwell1@reuters.com",
    username: "ebullerwell199",
    password: bcrypt.hashSync("8IIYtNJqK7", 8),
    created_at: "2020-01-18",
  },
  {
    first_name: "Hugibert",
    last_name: "Kimm",
    email: "16hkimm2@vistaprint.com",
    username: "hkimm223",
    password: bcrypt.hashSync("YnrOdT", 8),
    created_at: "2020-03-18",
  },
  {
    first_name: "Boris",
    last_name: "Dignall",
    email: "48bdignall3@woothemes.com",
    username: "bdignall335",
    password: bcrypt.hashSync("qQZv2gm", 8),
    created_at: "2020-02-20",
  },
  {
    first_name: "Hurlee",
    last_name: "Holbie",
    email: "38hholbie4@bloomberg.com",
    username: "hholbie447",
    password: bcrypt.hashSync("pLOetgRI1YwE", 8),
    created_at: "2020-02-23",
  },
  {
    first_name: "Felicia",
    last_name: "Cawdell",
    email: "24fcawdell5@ca.gov",
    username: "fcawdell553",
    password: bcrypt.hashSync("tkeGAZb", 8),
    created_at: "2019-08-11",
  },
  {
    first_name: "Mario",
    last_name: "Bugg",
    email: "18mbugg6@naver.com",
    username: "mbugg634",
    password: bcrypt.hashSync("hjYYzhPTR", 8),
    created_at: "2019-09-27",
  },
  {
    first_name: "Ransell",
    last_name: "McIndrew",
    email: "23rmcindrew7@ibm.com",
    username: "rmcindrew726",
    password: bcrypt.hashSync("OdMLv1a2le", 8),
    created_at: "2019-08-29",
  },
  {
    first_name: "Corinne",
    last_name: "Dering",
    email: "77cdering8@webeden.co.uk",
    username: "cdering877",
    password: bcrypt.hashSync("k0FO7XL", 8),
    created_at: "2020-06-08",
  },
  {
    first_name: "Evangelin",
    last_name: "Bartlomiej",
    email: "83ebartlomiej9@fema.gov",
    username: "ebartlomiej936",
    password: bcrypt.hashSync("iHtIaB1", 8),
    created_at: "2019-11-23",
  },
  {
    first_name: "Osmond",
    last_name: "Chadwen",
    email: "37ochadwena@pbs.org",
    username: "ochadwena48",
    password: bcrypt.hashSync("8WnWf4", 8),
    created_at: "2020-05-27",
  },
  {
    first_name: "Jodi",
    last_name: "Sheldrake",
    email: "98jsheldrakeb@senate.gov",
    username: "jsheldrakeb68",
    password: bcrypt.hashSync("sFVoszOap", 8),
    created_at: "2019-09-06",
  },
  {
    first_name: "D'arcy",
    last_name: "Sonnenschein",
    email: "11dsonnenscheinc@cargocollective.com",
    username: "dsonnenscheinc38",
    password: bcrypt.hashSync("vsMuiUzSKjm", 8),
    created_at: "2019-08-15",
  },
  {
    first_name: "Truman",
    last_name: "Matussov",
    email: "72tmatussovd@amazon.co.uk",
    username: "tmatussovd22",
    password: bcrypt.hashSync("oDIayDSdp", 8),
    created_at: "2019-07-14",
  },
  {
    first_name: "Tait",
    last_name: "Le Floch",
    email: "4tlefloche@marketwatch.com",
    username: "tlefloche8",
    password: bcrypt.hashSync("wcfLuZFJKvUg", 8),
    created_at: "2020-02-24",
  },
  {
    first_name: "Ardelle",
    last_name: "O'Spellissey",
    email: "6aospellisseyf@time.com",
    username: "aospellisseyf47",
    password: bcrypt.hashSync("PuwiFxHo8S0t", 8),
    created_at: "2019-8-11",
  },
  {
    first_name: "Garrard",
    last_name: "Boughton",
    email: "7gboughtong@sogou.com",
    username: "gboughtong91",
    password: bcrypt.hashSync("z4nMoT2", 8),
    created_at: "2020-01-31",
  },
  {
    first_name: "Waylon",
    last_name: "Awdry",
    email: "48wawdryh@vimeo.com",
    username: "wawdryh25",
    password: bcrypt.hashSync("fDXePJYs", 8),
    created_at: "2019-07-28",
  },
  {
    first_name: "Helge",
    last_name: "Codner",
    email: "58hcodneri@miitbeian.gov.cn",
    username: "hcodneri19",
    password: bcrypt.hashSync("UHjIORJ6NGy", 8),
    created_at: "2019-11-26",
  },
  {
    first_name: "Temple",
    last_name: "Hruska",
    email: "7thruskaj@prlog.org",
    username: "thruskaj65",
    password: bcrypt.hashSync("rO0FENRAr", 8),
    created_at: "2020-05-18",
  },
  {
    first_name: "Bathsheba",
    last_name: "Cumming",
    email: "55bcummingk@blog.com",
    username: "bcummingk73",
    password: bcrypt.hashSync("ddhFMxKSG", 8),
    created_at: "2020-04-30",
  },
  {
    first_name: "Johannes",
    last_name: "Mazella",
    email: "61jmazellal@vk.com",
    username: "jmazellal14",
    password: bcrypt.hashSync("BR1IGYPWQ7", 8),
    created_at: "2019-8-06",
  },
  {
    first_name: "Hillery",
    last_name: "Van Der Vlies",
    email: "23hvandervliesm@narod.ru",
    username: "hvandervliesm86",
    password: bcrypt.hashSync("v7gYoDEU", 8),
    created_at: "2020-01-16",
  },
  {
    first_name: "Reuben",
    last_name: "Ambrosi",
    email: "55rambrosin@squarespace.com",
    username: "rambrosin25",
    password: bcrypt.hashSync("KsLPABg9BoeY", 8),
    created_at: "2019-09-17",
  },
  {
    first_name: "Ula",
    last_name: "Shearstone",
    email: "0ushearstoneo@wsj.com",
    username: "ushearstoneo57",
    password: bcrypt.hashSync("6UO1xPgPJF", 8),
    created_at: "2020-02-26",
  },
  {
    first_name: "Gilda",
    last_name: "Arrighini",
    email: "80garrighinip@wikia.com",
    username: "garrighinip85",
    password: bcrypt.hashSync("VYbXoWHs15T", 8),
    created_at: "2020-02-29",
  },
  {
    first_name: "Devina",
    last_name: "Abramov",
    email: "91dabramovq@sbwire.com",
    username: "dabramovq72",
    password: bcrypt.hashSync("VyeMRpzixGS1", 8),
    created_at: "2020-06-17",
  },
  {
    first_name: "Grenville",
    last_name: "Walentynowicz",
    email: "56gwalentynowiczr@zimbio.com",
    username: "gwalentynowiczr57",
    password: bcrypt.hashSync("md31WA", 8),
    created_at: "2019-08-18",
  },
  {
    first_name: "Carson",
    last_name: "Baigrie",
    email: "4cbaigries@microsoft.com",
    username: "cbaigries43",
    password: bcrypt.hashSync("uKPLVXuCLAc", 8),
    created_at: "2020-03-15",
  },
  {
    first_name: "Hughie",
    last_name: "Ferran",
    email: "85hferrant@livejournal.com",
    username: "hferrant61",
    password: bcrypt.hashSync("yhlodzyuOkrx", 8),
    created_at: "2019-07-22",
  },
  {
    first_name: "Rosamond",
    last_name: "Northern",
    email: "77rnorthernu@oakley.com",
    username: "rnorthernu53",
    password: bcrypt.hashSync("AImh1f4KTM", 8),
    created_at: "2019-8-29",
  },
  {
    first_name: "Conchita",
    last_name: "Kilgrew",
    email: "91ckilgrewv@webnode.com",
    username: "ckilgrewv61",
    password: bcrypt.hashSync("XhzC7ziMCJ5R", 8),
    created_at: "2019-09-11",
  },
  {
    first_name: "Sabine",
    last_name: "Tough",
    email: "8stoughw@facebook.com",
    username: "stoughw39",
    password: bcrypt.hashSync("9Ka9kgA9", 8),
    created_at: "2020-05-22",
  },
  {
    first_name: "Anderea",
    last_name: "Channing",
    email: "44achanningx@infoseek.co.jp",
    username: "achanningx64",
    password: bcrypt.hashSync("gIv0KbspGdx", 8),
    created_at: "2019-08-01",
  },
  {
    first_name: "Velvet",
    last_name: "Cregg",
    email: "99vcreggy@networkadvertising.org",
    username: "vcreggy93",
    password: bcrypt.hashSync("5FA82cCJH", 8),
    created_at: "2019-07-28",
  },
  {
    first_name: "Cora",
    last_name: "Caukill",
    email: "53ccaukillz@utexas.edu",
    username: "ccaukillz41",
    password: bcrypt.hashSync("yWlFJ0Q0G", 8),
    created_at: "2019-8-29",
  },
  {
    first_name: "Casper",
    last_name: "De Nisco",
    email: "6cdenisco10@cbslocal.com",
    username: "cdenisco1069",
    password: bcrypt.hashSync("gQRwEcBSW", 8),
    created_at: "2019-11-19",
  },
  {
    first_name: "Arley",
    last_name: "De La Hay",
    email: "14adelahay11@google.nl",
    username: "adelahay1144",
    password: bcrypt.hashSync("2On17q7", 8),
    created_at: "2019-8-23",
  },
  {
    first_name: "Christie",
    last_name: "Ashingden",
    email: "29cashingden8@photobucket.com",
    username: "cashingden880",
    password: bcrypt.hashSync("ulzGTh5zZjX", 8),
    created_at: "2020-05-18",
  },
  {
    first_name: "Rafe",
    last_name: "Syalvester",
    email: "64rsyalvester13@freewebs.com",
    username: "rsyalvester1377",
    password: bcrypt.hashSync("G5XzpG6f", 8),
    created_at: "2019-11-25",
  },
  {
    first_name: "Boothe",
    last_name: "MacKaig",
    email: "60bmackaig14@nps.gov",
    username: "bmackaig1432",
    password: bcrypt.hashSync("WNLNBhpddEag", 8),
    created_at: "2019-09-28",
  },
  {
    first_name: "Lenna",
    last_name: "Simacek",
    email: "8lsimacek15@msn.com",
    username: "lsimacek1546",
    password: bcrypt.hashSync("pcBBU0OuZJdp", 8),
    created_at: "2020-05-23",
  },
  {
    first_name: "Tallie",
    last_name: "Greber",
    email: "23tgreber16@drupal.org",
    username: "tgreber1651",
    password: bcrypt.hashSync("ZW3R8D9", 8),
    created_at: "2020-01-27",
  },
  {
    first_name: "Godfrey",
    last_name: "Beecroft",
    email: "67gbeecroft17@shinystat.com",
    username: "gbeecroft1795",
    password: bcrypt.hashSync("GuD8LdkxAuX", 8),
    created_at: "2019-06-28",
  },
  {
    first_name: "Florenza",
    last_name: "Bourdice",
    email: "13fbourdice18@theguardian.com",
    username: "fbourdice1843",
    password: bcrypt.hashSync("zbhsOoP", 8),
    created_at: "2020-02-18",
  },
  {
    first_name: "Midge",
    last_name: "Comazzo",
    email: "69mcomazzo19@state.tx.us",
    username: "mcomazzo1964",
    password: bcrypt.hashSync("gEJiQv7pfcm", 8),
    created_at: "2020-03-26",
  },
  {
    first_name: "Von",
    last_name: "Gippes",
    email: "99vgippes1a@slashdot.org",
    username: "vgippes1a90",
    password: bcrypt.hashSync("2IF9TWmNC", 8),
    created_at: "2020-02-08",
  },
  {
    first_name: "Darrell",
    last_name: "Bard",
    email: "3dbard1b@mac.com",
    username: "dbard1b7",
    password: bcrypt.hashSync("B8twbU3CS", 8),
    created_at: "2020-04-06",
  },
  {
    first_name: "Lorilee",
    last_name: "Henrichsen",
    email: "76lhenrichsen1c@examiner.com",
    username: "lhenrichsen1c81",
    password: bcrypt.hashSync("RktABxjOqcaL", 8),
    created_at: "2019-11-8",
  },
  {
    first_name: "Benton",
    last_name: "Walwood",
    email: "65bwalwood1d@furl.net",
    username: "bwalwood1d26",
    password: bcrypt.hashSync("AEGfQj", 8),
    created_at: "2020-05-13",
  },
  {
    first_name: "Carmita",
    last_name: "Shemwell",
    email: "99cshemwell1e@jigsy.com",
    username: "cshemwell1e98",
    password: bcrypt.hashSync("4eA2zO", 8),
    created_at: "2019-8-13",
  },
  {
    first_name: "Saudra",
    last_name: "Paye",
    email: "58spaye1f@nationalgeographic.com",
    username: "spaye1f63",
    password: bcrypt.hashSync("Gbyb6bCDk,8)X", 8),
    created_at: "2019-09-14",
  },
  {
    first_name: "Corney",
    last_name: "Reimers",
    email: "41creimers1g@patch.com",
    username: "creimers1g83",
    password: bcrypt.hashSync("qcc5fzvYY,8)oi8", 8),
    created_at: "2020-05-08",
  },
  {
    first_name: "Wilden",
    last_name: "Clipston",
    email: "66wclipston1h@mayoclinic.com",
    username: "wclipston1h36",
    password: bcrypt.hashSync("aGll9zm", 8),
    created_at: "2020-05-30",
  },
  {
    first_name: "Durward",
    last_name: "MacGillacolm",
    email: "52dmacgillacolm1i@yahoo.co.jp",
    username: "dmacgillacolm1i21",
    password: bcrypt.hashSync("G8yFyNKf8,8)1wj", 8),
    created_at: "2019-09-28",
  },
  {
    first_name: "Hamish",
    last_name: "Betton",
    email: "83hbetton1j@mayoclinic.com",
    username: "hbetton1j87",
    password: bcrypt.hashSync("QeRAZQp", 8),
    created_at: "2020-05-31",
  },
  {
    first_name: "Archibold",
    last_name: "Yare",
    email: "74ayare1k@ycombinator.com",
    username: "ayare1k13",
    password: bcrypt.hashSync("lDdUUz01z,8)", 8),
    created_at: "2019-8-08",
  },
  {
    first_name: "Evelyn",
    last_name: "Cregin",
    email: "82ecregin1l@narod.ru",
    username: "ecregin1l97",
    password: bcrypt.hashSync("166kwfKU0,8)", 8),
    created_at: "2020-01-28",
  },
  {
    first_name: "Iver",
    last_name: "Bohin",
    email: "47ibohin1m@weibo.com",
    username: "ibohin1m53",
    password: bcrypt.hashSync("Q8n6LlKHv,8)eTG", 8),
    created_at: "2020-04-10",
  },
  {
    first_name: "Carrol",
    last_name: "Hexam",
    email: "95chexam1n@ask.com",
    username: "chexam1n43",
    password: bcrypt.hashSync("ILegBd", 8),
    created_at: "2019-8-25",
  },
  {
    first_name: "Marlow",
    last_name: "Nisen",
    email: "73mnisen1o@icio.us",
    username: "mnisen1o4",
    password: bcrypt.hashSync("6riFkVLe", 8),
    created_at: "2020-06-19",
  },
  {
    first_name: "Roger",
    last_name: "Passion",
    email: "97rpassion1p@amazon.de",
    username: "rpassion1p54",
    password: bcrypt.hashSync("OscD6LymG,8)sWK", 8),
    created_at: "2019-07-24",
  },
  {
    first_name: "Gayel",
    last_name: "Litterick",
    email: "22glitterick1q@prweb.com",
    username: "glitterick1q37",
    password: bcrypt.hashSync("b6mT1Z", 8),
    created_at: "2019-08-08",
  },
  {
    first_name: "Sissie",
    last_name: "Keough",
    email: "65skeough1r@pagesperso-orange.fr",
    username: "skeough1r10",
    password: bcrypt.hashSync("UCX1fc", 8),
    created_at: "2020-03-24",
  },
  {
    first_name: "Lynde",
    last_name: "Rome",
    email: "3lrome1s@auda.org.au",
    username: "lrome1s89",
    password: bcrypt.hashSync("xTwTarl", 8),
    created_at: "2019-11-01",
  },
  {
    first_name: "Kalindi",
    last_name: "Gosney",
    email: "20kgosney1t@home.pl",
    username: "kgosney1t55",
    password: bcrypt.hashSync("b8rZQxAmr,8)R", 8),
    created_at: "2019-06-30",
  },
  {
    first_name: "Maurizia",
    last_name: "Castellone",
    email: "95mcastellone1u@nsw.gov.au",
    username: "mcastellone1u1",
    password: bcrypt.hashSync("J5jEYrQ5", 8),
    created_at: "2020-01-15",
  },
  {
    first_name: "Monah",
    last_name: "Skelington",
    email: "34mskelington1v@devhub.com",
    username: "mskelington1v80",
    password: bcrypt.hashSync("XJH7xF8RY,8)gB", 8),
    created_at: "2019-09-06",
  },
  {
    first_name: "Godfrey",
    last_name: "Ninotti",
    email: "70gninotti1w@delicious.com",
    username: "gninotti1w74",
    password: bcrypt.hashSync("PkZEDax", 8),
    created_at: "2020-01-30",
  },
  {
    first_name: "Henrik",
    last_name: "Dresche",
    email: "96hdresche1x@parallels.com",
    username: "hdresche1x2",
    password: bcrypt.hashSync("CUSm1d2", 8),
    created_at: "2019-10-8",
  },
  {
    first_name: "Marijo",
    last_name: "Winterton",
    email: "69mwinterton1y@csmonitor.com",
    username: "mwinterton1y8",
    password: bcrypt.hashSync("l6rQks", 8),
    created_at: "2019-10-24",
  },
  {
    first_name: "Brucie",
    last_name: "Cabena",
    email: "78bcabena1z@printfriendly.com",
    username: "bcabena1z58",
    password: bcrypt.hashSync("uB9yoT", 8),
    created_at: "2020-03-29",
  },
  {
    first_name: "Caldwell",
    last_name: "Hrycek",
    email: "40chrycek20@forbes.com",
    username: "chrycek2084",
    password: bcrypt.hashSync("6OzRuVEWX,8)z", 8),
    created_at: "2019-09-23",
  },
  {
    first_name: "Fabe",
    last_name: "Unitt",
    email: "34funitt21@go.com",
    username: "funitt2133",
    password: bcrypt.hashSync("w6FOUGLJ", 8),
    created_at: "2020-01-26",
  },
  {
    first_name: "Jennie",
    last_name: "O' Liddy",
    email: "49joliddy22@statcounter.com",
    username: "joliddy2262",
    password: bcrypt.hashSync("RzRR6EcWY,8)sN", 8),
    created_at: "2019-11-09",
  },
  {
    first_name: "Kellie",
    last_name: "Cicchitello",
    email: "55kcicchitello23@umich.edu",
    username: "kcicchitello2375",
    password: bcrypt.hashSync("mHVgbeF", 8),
    created_at: "2020-04-29",
  },
  {
    first_name: "Pippo",
    last_name: "Joist",
    email: "14pjoist24@eepurl.com",
    username: "pjoist2465",
    password: bcrypt.hashSync("mbEP5s", 8),
    created_at: "2019-11-28",
  },
  {
    first_name: "Arlena",
    last_name: "Betjes",
    email: "52abetjes25@storify.com",
    username: "abetjes2585",
    password: bcrypt.hashSync("eA7NMk7R", 8),
    created_at: "2019-08-30",
  },
  {
    first_name: "Robbi",
    last_name: "Hatwells",
    email: "79rhatwells26@japanpost.jp",
    username: "rhatwells263",
    password: bcrypt.hashSync("nZFreHuXQ,8)wN", 8),
    created_at: "2020-03-04",
  },
  {
    first_name: "Riccardo",
    last_name: "Roddell",
    email: "84rroddell27@vimeo.com",
    username: "rroddell2733",
    password: bcrypt.hashSync("H52PmI9eF,8)jj", 8),
    created_at: "2020-01-22",
  },
  {
    first_name: "Burnard",
    last_name: "Wellings",
    email: "61bwellings28@seattletimes.com",
    username: "bwellings2836",
    password: bcrypt.hashSync("SHT9Mh7Xz,8)YT", 8),
    created_at: "2020-03-17",
  },
  {
    first_name: "Tommy",
    last_name: "Morriss",
    email: "66tmorriss29@vinaora.com",
    username: "tmorriss2932",
    password: bcrypt.hashSync("MoKOng4r1,8)6q", 8),
    created_at: "2019-09-04",
  },
  {
    first_name: "Iolande",
    last_name: "Dikle",
    email: "69idikle2a@cocolog-nifty.com",
    username: "idikle2a65",
    password: bcrypt.hashSync("EzhQopdlA,8)LPj", 8),
    created_at: "2019-07-15",
  },
  {
    first_name: "Trueman",
    last_name: "Panther",
    email: "61tpanther2b@reference.com",
    username: "tpanther2b32",
    password: bcrypt.hashSync("FKjnTgwtG,8)b", 8),
    created_at: "2020-06-09",
  },
  {
    first_name: "Shayne",
    last_name: "Frain",
    email: "46sfrain2c@youtube.com",
    username: "sfrain2c8",
    password: bcrypt.hashSync("9Bp1kq0", 8),
    created_at: "2020-04-29",
  },
  {
    first_name: "Jeth",
    last_name: "Recher",
    email: "46jrecher2d@yelp.com",
    username: "jrecher2d22",
    password: bcrypt.hashSync("mANUI6bhc,8)5UC", 8),
    created_at: "2019-09-29",
  },
  {
    first_name: "Cristabel",
    last_name: "Ennals",
    email: "21cennals2e@networksolutions.com",
    username: "cennals2e76",
    password: bcrypt.hashSync("JteiF0Uc", 8),
    created_at: "2019-07-19",
  },
  {
    first_name: "Cary",
    last_name: "Suddaby",
    email: "33csuddaby2f@home.pl",
    username: "csuddaby2f49",
    password: bcrypt.hashSync("RqGKLvHYO,8)", 8),
    created_at: "2020-05-25",
  },
  {
    first_name: "Vassili",
    last_name: "Ariss",
    email: "41variss2g@narod.ru",
    username: "variss2g1",
    password: bcrypt.hashSync("Ksa7QX", 8),
    created_at: "2019-11-26",
  },
  {
    first_name: "Lyda",
    last_name: "Gummie",
    email: "22lgummie2h@constantcontact.com",
    username: "lgummie2h18",
    password: bcrypt.hashSync("XDKR8c1fX,8)", 8),
    created_at: "2020-05-25",
  },
  {
    first_name: "Bradly",
    last_name: "Murdoch",
    email: "31bmurdoch2i@deliciousdays.com",
    username: "bmurdoch2i49",
    password: bcrypt.hashSync("bUKj233eB,8)d", 8),
    created_at: "2020-05-27",
  },
  {
    first_name: "Angeli",
    last_name: "Grammer",
    email: "28agrammer2j@squarespace.com",
    username: "agrammer2j91",
    password: bcrypt.hashSync("pxFfktTqh,8)E", 8),
    created_at: "2020-05-21",
  },
  {
    first_name: "Ginger",
    last_name: "Hemphall",
    email: "34ghemphall2k@icio.us",
    username: "ghemphall2k16",
    password: bcrypt.hashSync("4bstvludY,8)2aa", 8),
    created_at: "2020-04-08",
  },
  {
    first_name: "Rikki",
    last_name: "Heninghem",
    email: "80rheninghem2l@xing.com",
    username: "rheninghem2l89",
    password: bcrypt.hashSync("V4J0IAkA", 8),
    created_at: "2019-11-02",
  },
  {
    first_name: "Chelsae",
    last_name: "Davana",
    email: "77cdavana2m@icio.us",
    username: "cdavana2m59",
    password: bcrypt.hashSync("YtzKWoVG4,8)", 8),
    created_at: "2020-03-13",
  },
  {
    first_name: "Hansiain",
    last_name: "Fendt",
    email: "20hfendt2n@shareasale.com",
    username: "hfendt2n14",
    password: bcrypt.hashSync("OokxsO", 8),
    created_at: "2019-11-14",
  },
  {
    first_name: "Nikki",
    last_name: "O' Liddy",
    email: "63noliddy2o@usnews.com",
    username: "noliddy2o54",
    password: bcrypt.hashSync("Z0Il56ipL,8)dN", 8),
    created_at: "2019-10-20",
  },
  {
    first_name: "Cassondra",
    last_name: "Sirrell",
    email: "74csirrell2p@weather.com",
    username: "csirrell2p30",
    password: bcrypt.hashSync("JoHeCIt1c,8)NI", 8),
    created_at: "2020-05-03",
  },
  {
    first_name: "Vannie",
    last_name: "La Grange",
    email: "88vlagrange2q@sina.com.cn",
    username: "vlagrange2q53",
    password: bcrypt.hashSync("T9qrFOmcR,8)", 8),
    created_at: "2020-02-08",
  },
  {
    first_name: "Kristos",
    last_name: "Pond-Jones",
    email: "64kpondjones2r@infoseek.co.jp",
    username: "kpondjones2r99",
    password: bcrypt.hashSync("NRWMepaC", 8),
    created_at: "2019-11-05",
  },
];
